Added `addon::create` command
cscart/sdk pull request #8
Opened 2022-02-12 10:29 UTC by hacker-cb

Addon directories structure  is very compilcated and it not very to create all needed folder manually without mistakes.

So, I added `addon::create` command which will:

- Create addon directory structure.
- Create addon.xml.
- Create language files templates.

If directory or file exists it will skip it, never overwrite. So, it is safe to run this command in the existing addons folders.

2022-02-15 13:09 UTC, torunar requested changes

2022-02-15 13:09 UTC, torunar commented on src/Sdk/Commands/AddonCreateCommand.php
> +            $output->writeln(sprintf('Manifest already exists "%s", <info>skipping</info>',
Manifest — это терминология тем. Для модулей используется термин "схема"/scheme:
https://docs.cs-cart.com/latest/developer_guide/addons/addon_scheme.html
https://www.cs-cart.ru/docs/latest/developer_guide/addons/addon_scheme.html

2022-02-15 13:09 UTC, torunar commented on src/Sdk/Commands/AddonCreateCommand.php
> +                $po_content = $this->twig()->render('addon/lang/'.$lang.'.po.twig', [
```suggestion
                $po_content = $this->twig()->render('addon/lang/' . $lang . '.po.twig', [
```

2022-02-15 13:09 UTC, torunar commented on src/Sdk/Commands/AddonCreateCommand.php
> +            $po_file = "var/langs/$lang/addons/$addon_id.po";
```suggestion
            $po_file = "var/langs/{$lang}/addons/{$addon_id}.po";
```

2022-02-15 13:09 UTC, torunar commented on bin/cscart-sdk
> +const CSCART_SDK_ROOT = __DIR__ . '/..';
Лучше передавать как зависимость в конкретные команды, которым это нужно.

2022-02-15 13:09 UTC, torunar commented on README.md
> +  -l, --language=LANGUAGE  Languages [default: ["en","ru"]] (multiple values allowed)
В CS-Cart поддерживаются схемы двух версий: 3 и 4, эта команда поддерживает только третью версию.
Чтобы в будущем можно было расширить поведение, я бы уже сейчас добавил параметр, отвечающий за версию схемы и вынес все специфичные для этой версии вещи в отдельный сервис.

2022-02-15 13:09 UTC, torunar commented on templates/addon/lang/ru.po.twig
> +"Language: ru_RU\n"
Такая реализация позволит создавать модули только на английском и русском языках. От такого ограничения хотелось бы уйти, и вот как можно это сделать:
1. Вместо кодов en и ru передавать в команду коды локалей en_US, ru_RU.
2. Хранить шаблон "универсального" файла переводов с параметризованным Language:
```suggestion
"Language: {{locale}}\n"
```
3. При создании файла переводов подставлять код локали, по коду же локали определять название .po-файла: en_US -> en.po, ru_RU -> ru.po.

2022-02-15 14:34 UTC, hacker-cb commented on bin/cscart-sdk
> +const CSCART_SDK_ROOT = __DIR__ . '/..';
Fixed in https://github.com/hacker-cb/sdk/commit/5860c92f952d28b63e0a493ce2ce0987439d9233

2022-02-15 14:37 UTC, hacker-cb commented on src/Sdk/Commands/AddonCreateCommand.php
> +            $output->writeln(sprintf('Manifest already exists "%s", <info>skipping</info>',
Fixed in https://github.com/hacker-cb/sdk/commit/21a8dc4e52be3c2f3c5dc34324a464a858045ce3

2022-02-15 14:48 UTC, hacker-cb commented on README.md
> +  -l, --language=LANGUAGE  Languages [default: ["en","ru"]] (multiple values allowed)
Судя по доке, версия 2 и 3 (а не 3 и 4).
Вы  опечатались, или планируется 4 версия?

Fixed in https://github.com/hacker-cb/sdk/commit/35b8a02d91bca0404beedebdd6492db03e00f8e7

2022-02-15 14:49 UTC, hacker-cb commented on templates/addon/lang/ru.po.twig
> +"Language: ru_RU\n"
`Language-Team` тогда убираю, он не обязательный?

2022-02-15 15:11 UTC, hacker-cb commented on templates/addon/lang/ru.po.twig
> +"Language: ru_RU\n"
Fixed in https://github.com/hacker-cb/sdk/commit/28b794fb16efd2b969d4048d1ff178b11ad9890a

`Language-Team` убрал. Или он все-таки нужен?

2022-02-25 13:49 UTC, torunar requested changes

2022-02-25 13:49 UTC, torunar commented on src/Sdk/Commands/Traits/TwigEnvironmentTrait.php
> +            $_SERVER['HOME'] . '/.cscart-sdk/templates',
Команда падает с фатальной ошибкой, если папка с собственными шаблонами не существует.
```
In FilesystemLoader.php line 92:

  The "/home/torunar/.cscart-sdk/templates" directory does not exist ("/home/torunar/.cscart-sdk/templates").

```

2022-03-01 12:58 UTC, merged

2022-03-01 12:58 UTC, torunar commented
@hacker-cb Great job! Thank you.